#!/bin/bash
# NOTE: This file is automatically pulled from GitHub and used within this launch template:
# https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#LaunchTemplateDetails:launchTemplateId=lt-031648d4e4611879f

# Install dependencies
yum install -y python3-pip

pip3 install boto3 botocore requests

wget https://raw.githubusercontent.com/aidando73/hello-runpod-api/refs/heads/main/watch_runpod_availability.py -O /home/ec2-user/watch_runpod_availability.py

# Create a systemd service file
cat > /etc/systemd/system/runpod-watcher.service << 'EOL'
[Unit]
Description=RunPod Availability Watcher
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 /home/ec2-user/watch_runpod_availability.py
Environment="PYTHONUNBUFFERED=1"
Restart=always
User=ec2-user
StandardOutput=append:/var/log/runpod-watcher.log
StandardError=append:/var/log/runpod-watcher.log

[Install]
WantedBy=multi-user.target
EOL

systemctl enable runpod-watcher
systemctl start runpod-watcher
